# Generated by Django 4.2.6 on 2023-10-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_source_location_item_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_location',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
